### ISSUE TITLE
一个问题可以帮我看下怎么解决吗

### ISSUE THREAD

**Issue by rock-lss** [mdyao/CSNorm#9]
Traceback (most recent call last):
  File "/homec/ssli/CSNorm/train.py", line 223, in <module>
    main()
  File "/homec/ssli/CSNorm/train.py", line 38, in main
    opt = option.parse(args.opt, is_train=True)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/homec/ssli/CSNorm/options/options.py", line 18, in parse
    scale = opt['scale']
            ~~~^^^^^^^^^
KeyError: 'scale'

**Comment by rock-lss** [comment]
我刚刚看了一下这个scale在文件中确实没定义，是需要自己定义吗

**Comment by CX1888** [comment]
> Traceback (most recent call last): File "/homec/ssli/CSNorm/train.py", line 223, in main() File "/homec/ssli/CSNorm/train.py", line 38, in main opt = option.parse(args.opt, is_train=True) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/homec/ssli/CSNorm/options/options.py", line 18, in parse scale = opt['scale'] ~~~^^^^^^^^^ KeyError: 'scale'

modify scale = opt['scale'] to scale = opt['network_G']['scale'], and here you go.
